- name: Adding Manager Replicas
  shell: >
    docker run -t --rm docker/dtr:{{DTR_Ver}} join --ucp-node `hostname` --ucp-insecure-tls --ucp-password {{UCP_Admin_Pass}} --ucp-url {{UCP_URL}} \
    --ucp-username {{UCP_Admin}} --existing-replica-id {{hostvars[groups['UCP-DTR'][0]]['replicaid']['stdout']}}
