# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export http_proxy=http://<proxy-host:port/
export https_proxy=http://<proxy-host:port/
export no_proxy=localhost,127.0.0.0/8,<comma separated list of ip addresses of cluster nodes>
export PATH
